-- AlterTable
ALTER TABLE "deals" ADD COLUMN     "giltCurve" DOUBLE PRECISION DEFAULT 0.042,
ADD COLUMN     "inflationCurve" DOUBLE PRECISION DEFAULT 0.031,
ADD COLUMN     "soniaCurve" DOUBLE PRECISION DEFAULT 0.0377;
